#!/bin/bash
S_EXEC=$(basename $0)

case $S_EXEC in
  *"pecc"      ) COMP=$PE_CC;;
  *"pec++"     ) COMP=$PE_CXX;;
  *"pefortran" ) COMP=$PE_FORTRAN;;
esac

if [ "$1" == "--pe-verbose" ]; then
  pe_verbose=1
  shift
fi

PACKAGES=$(echo $PE_PKGCONFIG_LIBS | tr ":" " ")
if [ ! -z "$PACKAGES" -a "$PAKCAGES" != " " ]; then
  if [ $pe_verbose ]; then
    echo "$S_EXEC: $COMP -Wl,--as-needed \"$@\" `pkg-config --cflags --libs $PACKAGES`"
  fi
  $COMP $PE_PRE_FLAGS -Wl,--as-needed "$@" \
        `pkg-config --cflags --libs $PACKAGES` $PE_POST_FLAGS
else
  if [ $pe_verbose ]; then
    echo "$S_EXEC: $COMP $@"
  fi
  $COMP $PE_PRE_FLAGS "$@" $PE_POST_FLAGS
fi

